version: '3'

env:
  ARTIFACTORY_URI: "https://artefacts.tax.service.gov.uk/artifactory"

tasks:
  local-test:
    desc: Run gradlew clean build command locally
    cmds:
    # "build" includes running tests
    # Using "--info" to see plugin versions, and errors
    # Using "--console=plain" to avoid colour escape codes in output when diverting to a log file
    - ./gradlew clean build --info --console=plain

  docker-test:
    desc: Run gradlew clean build command in docker container
    vars:
      MACHINE:
        # Will be arm64 or x86_64
        sh: uname -m
    cmds:
    # Is much faster on native Mac arm64 when compiled for arm64
    - docker build . --platform "linux/{{.MACHINE}}" -t jenkins-job-builders
    - docker run jenkins-job-builders
